engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
ratings:
  paths:
  - "server/**/*.js"
  - "client/**/*.js"
exclude_paths:
- client/tests
- client/e2e
- server/tests
- scripts